### ISSUE TITLE
Music Problem

### ISSUE THREAD

**Issue by Krxzy** [HurricanoBot/Hurricano#34]
Whenever I run the command hr!play (name) it wont give me a response back and it wont play anything in vc, it doesnt even join vc. Im using the bot hosted by you. Any fix?

**Comment by Militia21** [comment]
Hey Krxzy! I'm just looking for any errors, will come back to you after I find something out.

**Comment by DragonZV** [comment]
We recently just switched our Discord.js version to v13, and music was built for v12. I'll fix it soon.

**Comment by Krxzy** [comment]
Also, why the fuck did my server get raided by the bot? It deleted basically every channel I've got in my server wtf

**Comment by DragonZV** [comment]
@Krxzy militia21's eval backfired, and he accidentally deleted alot of channels instead of our support server's channels.
