### ISSUE TITLE
Invalid 

### ISSUE THREAD

**Issue by Darker-Ink** [HurricanoBot/Hurricano#4]
Mmm Yes your Discord invite link is Invalid should look into that :)

**Comment by DragonZV** [comment]
oH

**Comment by DragonZV** [comment]
https://github.com/HurricanoBot/Hurricano/commit/8c736b77c54c5ef688d24404c08c6e6a3c262e35

**Comment by DragonZV** [comment]
![image](https://user-images.githubusercontent.com/70718540/114965961-ef681180-9e71-11eb-9bb3-55e8d80da6f0.png)
