### ISSUE TITLE
bot doesn't want to live

### ISSUE THREAD

**Issue by Snzy027** [HurricanoBot/Hurricano#40]
The shard has an error, and the bot won't go online

**Comment by DragonZV** [comment]
> The shard has an error, and the bot won't go online

...what is the error?

**Comment by Snzy027** [comment]
there is an inscription (manager destroy) on the shard

**Comment by Snzy027** [comment]
![IMG_20210713_145810](https://user-images.githubusercontent.com/85831601/125414187-fd500241-2821-4a84-9e16-8c1dd2ced2c4.jpg)
like this

**Comment by DragonZV** [comment]
> ![IMG_20210713_145810](https://user-images.githubusercontent.com/85831601/125414187-fd500241-2821-4a84-9e16-8c1dd2ced2c4.jpg)
> like this

enable intents
![image](https://user-images.githubusercontent.com/70718540/125415232-b8c9f2c5-d600-458b-bbc2-6849707cbb32.png)

**Comment by Snzy027** [comment]
Oke

**Comment by Snzy027** [comment]
Work

**Comment by DragonZV** [comment]
?

**Comment by Snzy027** [comment]
and one more thing, why isn't the emoji showing up?
![Uploading IMG_20210713_151354.jpg…]()

**Comment by Snzy027** [comment]
![Uploading IMG_20210713_151354.jpg…]()

**Comment by Snzy027** [comment]
and one more thing, why isn't the emoji showing up? 
![Uploading IMG_20210713_151354.jpg…]()

**Comment by Snzy027** [comment]
and one more thing, why isn't the emoji showing up in help menu?

**Comment by DragonZV** [comment]
> and one more thing, why isn't the emoji showing up in help menu?

bot/utilities/emojis.json

**Comment by Snzy027** [comment]
![Uploading IMG_20210713_151354.jpg…]()

**Comment by Snzy027** [comment]
![IMG_20210713_151354](https://user-images.githubusercontent.com/85831601/125418169-e42322c4-28e3-4c84-83e2-e25d5c9f712c.jpg)

**Comment by DragonZV** [comment]
> > and one more thing, why isn't the emoji showing up in help menu?
> 
> bot/utilities/emojis.json

...like I said,

**Comment by Snzy027** [comment]
ok thanks, even though i don't understand heheheh

**Comment by DragonZV** [comment]
change /bot/utilities/emojis.json

**Comment by Snzy027** [comment]
the requirements?

**Comment by DragonZV** [comment]
...?

**Comment by Snzy027** [comment]
![IMG_20210713_163628](https://user-images.githubusercontent.com/85831601/125429337-247d8ab1-7def-4d74-bf20-6d58d6a34d77.jpg)
Why is this?, The "muterole" command doesn't work, and in the logs it says something like that

**Comment by DragonZV** [comment]
what is the error?

**Comment by DragonZV** [comment]
Oh nvm

**Comment by DragonZV** [comment]
You require filling up all the emojis in emojis.json

**Comment by Snzy027** [comment]
Can you fix antispam?

**Comment by DragonZV** [comment]
No

**Comment by Snzy027** [comment]
why?, you're the developer right?

**Comment by DragonZV** [comment]
its harder than just saying it
