### ISSUE TITLE
Problem with help command

### ISSUE THREAD

**Issue by r4club** [HurricanoBot/Hurricano#43]
[2021-07-16 15:27:25] - [warn]: Cannot read property 'join' of undefined
{
  "stack": "TypeError: Cannot read property 'join' of undefined
    at generateHelpEmbed (C:\\Users\
ikol\\OneDrive\\Imágenes\\Escritorio\\botki now live\\Hurricano-main\\bot\\comma
nds\\information\\help.js:201:50)
    at Command.run (C:\\Users\
ikol\\OneDrive\\Imágenes\\Escritorio\\botki now live\\Hurricano-main\\bot\\comma
nds\\information\\help.js:237:21)
    at MessageEvent.run (C:\\Users\
ikol\\OneDrive\\Imágenes\\Escritorio\\botki now live\\Hurricano-main\\bot\\event
s\\bot\\message.js:433:21)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)"
}
  

At the console 

and the  help command with mention or prefix dont work in the chat pls help me!!

**Comment by achaljhawar** [comment]
you have not defined `join` in 
````
C:\Users
ikol\OneDrive\Imágenes\Escritorio\botki now live\Hurricano-main\bot\comma
nds\information\help.js
````
so now just define it

**Comment by achaljhawar** [comment]
what did you add in your config.json file

**Comment by DragonZV** [comment]
You've probably deleted the image commands category, or renamed it
