### ISSUE TITLE
I deployed the main branch in heroku...

### ISSUE THREAD

**Issue by nostorian** [HurricanoBot/Hurricano#49]
i deployed the main branch in heroku with the config.json file completely filled and deployed, the deployment succeeded, but the bot didn't come only, i can't figure how to see the deploy logs, can someone help?

**Comment by DragonZV** [comment]
https://devcenter.heroku.com/articles/logging

**Comment by nostorian** [comment]
i ran it with my machine but guess commands are broken ig, so i will wait for the remake
